repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
        exclude: .*/k8s/.*/templates/.*\.yaml$
      - id: check-json
      - id: detect-private-key
      - id: pretty-format-json
        args: [
          '--autofix',
          '--indent', '4',
          '--no-sort-keys',
        ]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
        exclude: \.terraform\/.*$
  - repo: local
    hooks:
      - id: helmlint
        name: Run helm lint using values.yaml and environment values files
        entry: .hooks/helmlint.sh
        language: script
        files: \.((ya?ml)|(tpl))$
